// src/ai/types.ts
/**
 * Platform-level streaming event sent to clients.
 * Generated by EventConverter from SDKMessage.
 */
export type AgentStreamEvent =
  | { type: 'text_delta'; delta: string; contentIndex: number }
  | { type: 'tool_use_start'; id: string; name: string }
  | { type: 'tool_use_delta'; id: string; argsDelta: string }
  | { type: 'tool_result'; id: string; result: unknown; isError?: boolean }
  | { type: 'assistant_message'; message: unknown; sessionId: string }
  | { type: 'session_done'; sessionId: string; isError: boolean; cost?: number; turns?: number; duration?: number };

/**
 * LLM call options for AgentService.stream()
 */
export interface AgentCallOptions {
  prompt: string;
  sessionId?: string;
  systemPrompt?: string;
  allowedTools?: string[];
  abortSignal?: AbortSignal;
}